part2:
	g++ -std=c++11 -Wall -Wextra -fsanitize=address,undefined,leak main.cpp time_utility.cpp -o main.out
	./main.out

build:
	g++ -std=c++11 -Wall -Wextra -fsanitize=address,undefined,leak main.cpp time_utility.cpp -o main.out

run:
	./main.out

clean:
	rm -f main.out